[workspace]
authors = ["krishan rana"]
channels = ["conda-forge", "nmarticorena"]
name = "panda_dc"
platforms = ["linux-64"]
version = "0.1.0"


[environments]
dev = ["dev"]

[tasks]

[dependencies]
python="3.11.*"
reactivex = ">=4.0.4,<5"
numpy = ">=2"
scikit-build-core = ">=0.11.6,<0.12"
cmake = ">=4.1.2,<5"
hatchling = ">=1.27.0,<2"
matplotlib = ">=3.10.7,<4"
pip = ">=25.2,<26"
tyro = ">=0.9.35,<0.10"
libfranka = {version = "==0.9.2", channel = "nmarticorena"}
pyrealsense2 = ">=2.56.5,<3"
py-opencv = ">=4.12.0,<5"
threadpoolctl = ">=3.6.0,<4"
ffmpeg = "<8"
jupyter = ">=1.1.1,<2"
inquirerpy = ">=0.3.4,<0.4"

[pypi-options]
no-build-isolation = ["swift-sim", "roboticstoolbox-python", "spatialgeometry", "spatialmath-python"]

[pypi-dependencies]
panda_dc = {path = ".", editable = true}
swift-sim = {git = "https://github.com/nmarticorena/swift.git"}
roboticstoolbox-python = {git = "https://github.com/nmarticorena/robotics-toolbox-python.git"}
spatialgeometry = {git = "https://github.com/nmarticorena/spatialgeometry.git"}
spatialmath-python = {git = "https://github.com/nmarticorena/spatialmath-python.git"}
dynamixel-sdk = ">=3.8.4, <4"
panda-python = ">=0.8.1, <0.9"
panda-desk = {git = "https://github.com/nmarticorena/panda_desk.git"}
atomics = ">=1.0.3, <2"

[activation.env]
PANDA_IP = "172.16.0.2"

[feature.dev.dependencies]
ruff = "*"

[feature.dev.tasks]
format = {cmd = "ruff format panda_dc/*"}
